name: CI

on:
  push:
    branches: [ master ]
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "Tests - ${{ matrix.ruby }} | ${{ matrix.gemfile }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "2.6"
          - "2.7"
          - "3.0"
          - "3.1"
        gemfile:
          - Gemfile
          - gemfiles/rack.gemfile
          - gemfiles/rails_5.gemfile
          - gemfiles/rails_6.gemfile
          - gemfiles/rails_7.gemfile
          - gemfiles/rails_edge.gemfile
        include:
          - ruby: ruby-head
            gemfile: Gemfile
        exclude:
          # Rails 5 can't run on Ruby 3
          - gemfile: gemfiles/rails_5.gemfile
            ruby: 3.0
          - gemfile: gemfiles/rails_5.gemfile
            ruby: 3.1
          # Raise 7 can't run on 2.6
          - gemfile: gemfiles/rails_7.gemfile
            ruby: 2.6
          - gemfile: gemfiles/rails_edge.gemfile
            ruby: 2.6
    continue-on-error: ${{ matrix.ruby == 'ruby-head' || contains(matrix.gemfile, 'edge') }}
    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Setup DB
        run: bundle exec rake db:setup
      - name: Run tests
        run: bundle exec rspec
